### ISSUE TITLE
Uncaught RangeError: Port should be > 0 and < 65536

### ISSUE THREAD

**Issue by Tjoosten** [cjsaylor/atom-irc#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [irc](https://github.com/cjsaylor/atom-irc) package, v0.2.9

### Stack Trace

Uncaught RangeError: Port should be > 0 and < 65536

```
At net.js:828

RangeError: Port should be > 0 and < 65536
  at connect (net.js:828:13)
  at Socket.connect (net.js:893:5)
  at Object.exports.connect.exports.createConnection (net.js:86:35)
  at Client.connect (/Users/tim/.atom/packages/irc/node_modules/irc/lib/irc.js:707:25)
  at Connector.module.exports.Connector.connect (/Users/tim/.atom/packages/irc/lib/connector.coffee:52:13)
  at Connector.connect (/Users/tim/.atom/packages/irc/lib/connector.coffee:1:1)
  at atom-workspace.<anonymous> (/Users/tim/.atom/packages/irc/lib/irc.coffee:34:15)
  at atom-workspace.handler (/Users/tim/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Users/tim/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Users/tim/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/tim/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Users/tim/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/tim/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Users/tim/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Users/tim/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -2:10.2 editor:newline (atom-text-editor.editor)
     -2:09.1 core:paste (atom-text-editor.editor)
     -2:07.6 core:move-up (atom-text-editor.editor)
  9x -2:07.3 core:move-left (atom-text-editor.editor)
     -2:05.3 core:move-up (atom-text-editor.editor)
  2x -2:04.8 core:move-right (atom-text-editor.editor)
  4x -2:00.8 core:save (atom-text-editor.editor)
     -1:32.5 editor:newline (atom-text-editor.editor)
     -1:31.2 core:paste (atom-text-editor.editor)
  4x -1:28.2 core:save (atom-text-editor.editor)
  8x -1:21.0 core:backspace (atom-text-editor.editor)
  9x -1:17.2 core:move-right (atom-text-editor.editor)
  7x -1:15.4 core:backspace (atom-text-editor.editor)
  9x -1:11.3 core:save (atom-text-editor.editor)
     -0:01.2 irc:connect (input.irc-input.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Sasquatch, v0.2.0
atom-beautify, v0.21.2
atom-jade, v0.1.0
bootstrap-3-snippetset, v0.0.6
break, v0.3.1
color-picker, v1.3.0
git-log, v0.2.0
http-status-codes, v1.0.2
irc, v0.2.9
linter, v0.10.0
php-getters-setters, v0.2.3
phpunit, v1.0.9
remote-edit, v1.6.3
sass-watch, v0.2.0
terminal-status, v1.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by cjsaylor** [comment]
Fixed.
