### ISSUE TITLE
Uncaught RangeError: port should be > 0 and < 65536: 0

### ISSUE THREAD

**Issue by timothyparez** [cjsaylor/atom-irc#14]
[Enter steps to reproduce below:]

1. Install the package
2. Select connect from the menu

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [irc](https://github.com/cjsaylor/atom-irc) package, v0.2.9

### Stack Trace

Uncaught RangeError: port should be > 0 and < 65536: 0

```
At net.js:913

RangeError: port should be > 0 and < 65536: 0
  at Socket.connect (net.js:913:13)
  at Object.exports.connect.exports.createConnection (net.js:93:35)
  at Client.connect (C:\Users\Timothy\.atom\packages\irc\node_modules\irc\lib\irc.js:707:25)
  at Connector.module.exports.Connector.connect (C:\Users\Timothy\.atom\packages\irc\lib\connector.coffee:52:13)
  at Connector.connect (C:\Users\Timothy\.atom\packages\irc\lib\connector.coffee:1:1)
  at atom-workspace.<anonymous> (C:\Users\Timothy\.atom\packages\irc\lib\irc.coffee:34:15)
  at atom-workspace.handler (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Timothy\AppData\Local\atom\app-0.179.0\resources\app\src\window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -0:07.1 irc:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
irc, v0.2.9
language-fsharp, v0.8.4
web-browser, v1.2.0

# Dev
No dev packages
```

**Comment by cjsaylor** [comment]
This should be covered in 0.30.0.
