### ISSUE TITLE
Failed to load the irc package

### ISSUE THREAD

**Issue by bhaskardabhi-oviyum** [cjsaylor/atom-irc#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [irc](https://github.com/cjsaylor/atom-irc) package 0.4.0

### Stack Trace

Failed to load the irc package

```
At The super constructor to "inherits" must not be null or undefined

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at /packages/irc/node_modules/irc/lib/irc.js:575:6)
    at /packages/irc/node_modules/irc/lib/irc.js:956:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/irc/lib/connector.coffee:2:7)
    at /packages/irc/lib/connector.coffee:1:1)
    at /packages/irc/lib/connector.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/irc/lib/irc.coffee:5:10)
    at /packages/irc/lib/irc.coffee:1:1)
    at /packages/irc/lib/irc.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-asana 0.0.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-laravel-log 0.0.0 
atom-ternjs 0.18.3 
atom-translator 0.2.1 
data-atom 0.25.2 
emmet 2.4.3 
git-time-machine 1.5.9 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
irc 0.4.0 
merge-conflicts 1.4.5 
minimap-highlight-selected 4.6.1 
php-cs-fixer 4.1.0 
phpfmt 1.0.0 
RebelChat 0.8.1 
termination 0.6.0 
```

**Comment by HebaruSan** [comment]
This appears to be a problem in the `node-irc` dependency. I submitted a fix here:
https://github.com/martynsmith/node-irc/pull/521

**Comment by Throne3d** [comment]
It doesn't look like the `node-irc` package is being updated or responding to pull requests / issues, which prompted me to create a fork, "irc-upd" (it can be found on GitHub [here](https://github.com/Throne3d/node-irc) and on NPM [here](https://www.npmjs.com/package/irc-upd)). I've been adding a bunch of tests, fixing some of the more major bugs, and trying to keep the development more active. (I created the fork mostly to improve the stability of a project that used node-irc as a dependency, [discord-irc](https://github.com/reactiflux/discord-irc), but it looks like there might be some independent interest.)

I'm not sure if there would be inclination to swap, but I've added a commit which should fix this [here](https://github.com/Throne3d/node-irc/commit/be27350aa4f9d2265f86aae8e71f031a0e6c78bf). A new version hasn't been released yet, so it won't work if you just point at the library, and it's also under a different name, so references to `irc` would have to be updated, but if you use the commit hash and do that you might be able to get it working in the meantime.

(**Edit**: [I released v0.8.0 yesterday](https://github.com/Throne3d/node-irc/releases/tag/v0.8.0), which includes this fix.)
